// Generated by scripts/generate-agent-catalog.mjs from agents/catalog.json. Do not edit.
import { parseAgentCatalog } from "./agent-catalog-schema";

export const agentCatalog = parseAgentCatalog(
  {
    "schemaVersion": 1,
    "agents": [
      {
        "id": "claude",
        "name": "Claude Code",
        "maker": "Anthropic",
        "description": "Work through code changes, debugging, and Git workflows with Claude in your terminal.",
        "url": "https://github.com/anthropics/claude-code",
        "iconUrl": "https://assets.claude.com/95a868946ac8a31e5ff832e2899f294aa368b836.png?w=128&h=128",
        "integratedHarness": "claude",
        "installation": {
          "commands": [
            "curl -fsSL https://claude.ai/install.sh | bash"
          ],
          "startCommand": "claude",
          "notes": "Requires macOS 13+ or a supported Linux distribution, and curl. Start Claude and follow the prompts to sign in with an eligible account or configure an API provider.",
          "setupUrl": "https://code.claude.com/docs/en/setup",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "rm -f \"$HOME/.local/bin/claude\" && rm -rf \"$HOME/.local/share/claude\""
          ],
          "url": "https://code.claude.com/docs/en/setup#uninstall-claude-code"
        }
      },
      {
        "id": "codex",
        "name": "Codex",
        "maker": "OpenAI",
        "description": "Read, edit, and run code with OpenAI’s coding agent in your local workspace.",
        "url": "https://github.com/openai/codex",
        "iconUrl": "https://github.com/openai.png?size=128",
        "integratedHarness": "codex",
        "installation": {
          "commands": [
            "curl -fsSL https://chatgpt.com/codex/install.sh | sh"
          ],
          "startCommand": "codex",
          "notes": "Requires curl. Start Codex in your project and sign in with ChatGPT, or configure an OpenAI API key.",
          "setupUrl": "https://github.com/openai/codex#quickstart",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "rm -f \"${CODEX_INSTALL_DIR:-$HOME/.local/bin}/codex\""
          ],
          "url": "https://github.com/openai/codex/blob/main/scripts/install/install.sh",
          "note": "Removes the native CLI launcher. Downloaded versions, settings, and sessions remain."
        }
      },
      {
        "id": "opencode",
        "name": "OpenCode",
        "maker": "Anomaly",
        "description": "An open source coding agent with a terminal interface and a choice of model providers.",
        "url": "https://github.com/anomalyco/opencode",
        "iconUrl": "https://avatars.githubusercontent.com/sst?s=128",
        "integratedHarness": "opencode",
        "installation": {
          "commands": [
            "curl -fsSL https://opencode.ai/install | bash"
          ],
          "startCommand": "opencode",
          "notes": "Requires curl and bash. In OpenCode, use /connect to choose and authenticate a model provider.",
          "setupUrl": "https://opencode.ai/docs/",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "opencode uninstall --keep-config --keep-data"
          ],
          "url": "https://opencode.ai/docs/cli/#uninstall",
          "note": "By default the uninstaller also deletes configuration and session data; --keep-config --keep-data limits it to program files."
        }
      },
      {
        "id": "hermes",
        "name": "Hermes Agent",
        "maker": "Nous Research",
        "description": "A general-purpose agent with memory, reusable skills, a terminal UI, and messaging connections.",
        "url": "https://github.com/NousResearch/hermes-agent",
        "iconUrl": "https://avatars.githubusercontent.com/NousResearch?s=128",
        "kind": "General-purpose agent",
        "installation": {
          "commands": [
            "curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash",
            "hermes setup"
          ],
          "startCommand": "hermes",
          "notes": "Requires curl and bash. Finish the setup wizard to choose a model provider and credentials. Open a new terminal if hermes is not yet on PATH.",
          "setupUrl": "https://github.com/NousResearch/hermes-agent#quick-install",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "hermes uninstall"
          ],
          "url": "https://nousresearch.github.io/hermes-agent/docs/getting-started/updating/",
          "note": "The uninstaller lets you keep your configuration."
        }
      },
      {
        "id": "openclaw",
        "name": "OpenClaw",
        "maker": "OpenClaw",
        "description": "A personal assistant on your own devices, connecting tools and messaging through a local gateway.",
        "url": "https://github.com/openclaw/openclaw",
        "iconUrl": "https://avatars.githubusercontent.com/openclaw?s=128",
        "kind": "General-purpose agent",
        "installation": {
          "commands": [
            "curl -fsSL https://openclaw.ai/install.sh | bash"
          ],
          "startCommand": "openclaw chat",
          "notes": "The installer provisions Node.js if needed and opens onboarding. Complete model setup, then use local terminal chat; messaging channels require a configured Gateway.",
          "setupUrl": "https://github.com/openclaw/openclaw#install",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "openclaw uninstall",
            "npm uninstall -g openclaw"
          ],
          "url": "https://docs.openclaw.ai/install/uninstall",
          "note": "First review service and data removal in the interactive uninstaller; then remove the CLI package."
        }
      },
      {
        "id": "pi",
        "name": "Pi",
        "maker": "Mario Zechner",
        "description": "A minimal coding harness you can shape with extensions, skills, prompt templates, and themes.",
        "url": "https://pi.dev/",
        "iconUrl": "https://avatars.githubusercontent.com/badlogic?s=128",
        "kind": "Coding harness",
        "installation": {
          "commands": [
            "npm install -g --ignore-scripts @earendil-works/pi-coding-agent"
          ],
          "startCommand": "pi",
          "notes": "Requires Node.js 22.19+ and npm. In Pi, use /login for a supported subscription provider, or configure a provider API key.",
          "setupUrl": "https://pi.dev/docs/latest/quickstart",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "npm uninstall -g @earendil-works/pi-coding-agent"
          ],
          "url": "https://pi.dev/docs/latest/quickstart#uninstall"
        }
      },
      {
        "id": "omp",
        "name": "omp",
        "maker": "Can Bölük",
        "description": "A Pi-based coding agent with a native Rust core, in-process search and shell tools, and IDE integration.",
        "url": "https://omp.sh/",
        "iconUrl": "https://omp.sh/favicon.png",
        "kind": "Coding harness",
        "installation": {
          "commands": [
            "curl -fsSL https://omp.sh/install | sh"
          ],
          "startCommand": "omp",
          "notes": "Requires curl. The installer uses Bun 1.3.14+ when present, otherwise a prebuilt binary in ~/.local/bin. Start omp in your project and follow its setup wizard to sign in to a provider; /login signs in again later.",
          "setupUrl": "https://omp.sh/docs/quickstart",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "rm -f \"${PI_INSTALL_DIR:-$HOME/.local/bin}/omp\""
          ],
          "url": "https://omp.sh/install",
          "note": "Removes the prebuilt binary. If the installer used Bun, run bun remove -g @oh-my-pi/pi-coding-agent instead."
        }
      },
      {
        "id": "fx",
        "name": "fx",
        "maker": "Vercel Labs",
        "description": "An experimental coding CLI written in Zig, with a Unix-style shell and an embeddable agent core.",
        "url": "https://github.com/vercel-labs/fx",
        "iconUrl": "https://github.com/vercel-labs.png?size=128",
        "kind": "Coding harness",
        "installation": {
          "commands": [
            "curl -fsSL https://fx.sh/setup.sh | bash",
            "fx login"
          ],
          "startCommand": "fx",
          "notes": "Experimental; supports x64 and ARM64 macOS/Linux. Requires curl and bash. fx login uses Vercel AI Gateway; fx setup accepts an API key.",
          "setupUrl": "https://github.com/vercel-labs/fx#install",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "rm -f \"${FX_INSTALL_DIR:-$HOME/.local/bin}/fx\""
          ],
          "url": "https://fx.sh/docs/getting-started/installation"
        }
      },
      {
        "id": "gemini",
        "name": "Gemini CLI",
        "maker": "Google",
        "description": "Bring Gemini to your terminal with file tools, shell commands, and Google Search grounding.",
        "url": "https://github.com/google-gemini/gemini-cli",
        "iconUrl": "https://github.com/google-gemini.png?size=128",
        "installation": {
          "commands": [
            "npm install -g @google/gemini-cli"
          ],
          "startCommand": "gemini",
          "notes": "Requires Node.js 20+ and npm. Official system guidance lists macOS 15+ or Ubuntu 20.04+. On first run, sign in with Google or configure a Gemini API key.",
          "setupUrl": "https://geminicli.com/docs/get-started/installation/",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "npm uninstall -g @google/gemini-cli"
          ],
          "url": "https://geminicli.com/docs/resources/uninstall/"
        }
      },
      {
        "id": "aider",
        "name": "Aider",
        "maker": "Aider",
        "description": "Pair program from the terminal, using a map of your repository and Git to track code edits.",
        "url": "https://github.com/Aider-AI/aider",
        "iconUrl": "https://avatars.githubusercontent.com/Aider-AI?s=128",
        "installation": {
          "commands": [
            "curl -LsSf https://aider.chat/install.sh | sh"
          ],
          "startCommand": "aider",
          "notes": "Requires curl. The installer supplies Python 3.12 if needed. Configure a model and its API key before coding; use --model to choose a model.",
          "setupUrl": "https://aider.chat/docs/install.html",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "uv tool uninstall aider-chat"
          ],
          "url": "https://aider.chat/docs/install.html"
        }
      },
      {
        "id": "goose",
        "name": "goose",
        "maker": "Agentic AI Foundation",
        "description": "An extensible local agent for code, research, and automation, with a CLI and MCP connections.",
        "url": "https://github.com/aaif-goose/goose",
        "iconUrl": "https://github.com/aaif-goose.png?size=128",
        "kind": "General-purpose agent",
        "installation": {
          "commands": [
            "curl -fsSL https://github.com/aaif-goose/goose/releases/download/stable/download_cli.sh | bash"
          ],
          "startCommand": "goose session",
          "notes": "Requires curl and bash. Follow the provider configuration prompts; goose configure can reopen setup. The CLI installs to ~/.local/bin.",
          "setupUrl": "https://goose-docs.ai/docs/getting-started/installation/",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "rm -f \"${GOOSE_BIN_DIR:-$HOME/.local/bin}/goose\""
          ],
          "url": "https://github.com/aaif-goose/goose/blob/main/download_cli.sh"
        }
      },
      {
        "id": "amp",
        "name": "Amp",
        "maker": "Amp",
        "description": "A coding agent that combines models and keeps work in threads across its CLI and other clients.",
        "url": "https://ampcode.com/docs",
        "iconUrl": "https://avatars.githubusercontent.com/sourcegraph?s=128",
        "installation": {
          "commands": [
            "curl -fsSL https://ampcode.com/install.sh | bash"
          ],
          "startCommand": "amp",
          "notes": "Requires curl and bash. Start Amp and sign in. Managed workspaces may provide their own installation instructions.",
          "setupUrl": "https://ampcode.com/docs/cli",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "rm -f \"$HOME/.local/bin/amp\" \"${AMP_HOME:-$HOME/.amp}/bin/amp\""
          ],
          "url": "https://ampcode.com/install.sh"
        }
      },
      {
        "id": "cursor",
        "name": "Cursor CLI",
        "maker": "Cursor",
        "description": "Use Cursor’s agent from the terminal for interactive coding sessions or scripted workflows.",
        "url": "https://cursor.com/docs/cli/overview",
        "iconUrl": "https://avatars.githubusercontent.com/getcursor?s=128",
        "installation": {
          "commands": [
            "curl https://cursor.com/install -fsS | bash"
          ],
          "startCommand": "agent",
          "notes": "Requires curl and bash. Ensure ~/.local/bin is on PATH, then run agent and follow the Cursor sign-in prompts.",
          "setupUrl": "https://cursor.com/docs/cli/installation",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "rm -f \"$HOME/.local/bin/agent\" \"$HOME/.local/bin/cursor-agent\" && rm -rf \"$HOME/.local/share/cursor-agent\""
          ],
          "url": "https://cursor.com/install"
        }
      },
      {
        "id": "copilot",
        "name": "GitHub Copilot CLI",
        "maker": "GitHub",
        "description": "Bring Copilot’s coding agent into your shell to explore projects and work through changes.",
        "url": "https://github.com/github/copilot-cli",
        "iconUrl": "https://github.com/github.png?size=128",
        "installation": {
          "commands": [
            "curl -fsSL https://gh.io/copilot-install | bash"
          ],
          "startCommand": "copilot",
          "notes": "Requires curl, bash, and an active Copilot subscription with CLI access enabled. Use /login inside Copilot when prompted.",
          "setupUrl": "https://github.com/github/copilot-cli#getting-started",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "rm -f \"${PREFIX:-$HOME/.local}/bin/copilot\""
          ],
          "url": "https://gh.io/copilot-install"
        }
      },
      {
        "id": "droid",
        "name": "Droid",
        "maker": "Factory",
        "description": "Factory’s terminal agent for project work, custom Droids, and headless automation.",
        "url": "https://docs.factory.ai/droid-cli/overview",
        "iconUrl": "https://github.com/Factory-AI.png?size=128",
        "installation": {
          "commands": [
            "curl -fsSL https://app.factory.ai/cli | sh"
          ],
          "startCommand": "droid",
          "notes": "Requires curl. Linux also needs xdg-utils. Start Droid in your project and follow the Factory browser sign-in prompts.",
          "setupUrl": "https://docs.factory.ai/droid-cli/quickstart",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "rm -f \"$HOME/.local/bin/droid\""
          ],
          "url": "https://app.factory.ai/cli"
        }
      },
      {
        "id": "crush",
        "name": "Crush",
        "maker": "Charm",
        "description": "A coding agent with a rich terminal UI and support for cloud and local model providers.",
        "url": "https://github.com/charmbracelet/crush",
        "iconUrl": "https://avatars.githubusercontent.com/charmbracelet?s=128",
        "installation": {
          "commands": [
            "npm install -g @charmland/crush"
          ],
          "startCommand": "crush",
          "notes": "Requires Node.js and npm. In Crush, open the model picker with Ctrl+L, choose a provider, and enter its API key.",
          "setupUrl": "https://github.com/charmbracelet/crush#installation",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "npm uninstall -g @charmland/crush"
          ],
          "url": "https://github.com/charmbracelet/crush"
        }
      },
      {
        "id": "qwen",
        "name": "Qwen Code",
        "maker": "Qwen",
        "description": "An open source terminal coding agent with skills, subagents, and multiple model API formats.",
        "url": "https://github.com/QwenLM/qwen-code",
        "iconUrl": "https://avatars.githubusercontent.com/QwenLM?s=128",
        "installation": {
          "commands": [
            "npm install -g @qwen-code/qwen-code@latest"
          ],
          "startCommand": "qwen",
          "notes": "Requires Node.js 22+ and npm. Run /auth inside Qwen Code to configure a provider and credentials.",
          "setupUrl": "https://github.com/QwenLM/qwen-code#installation",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "npm uninstall -g @qwen-code/qwen-code"
          ],
          "url": "https://github.com/QwenLM/qwen-code"
        }
      },
      {
        "id": "kimi",
        "name": "Kimi Code CLI",
        "maker": "Moonshot AI",
        "description": "A terminal coding agent with a shell command mode for moving between prompts and commands.",
        "url": "https://github.com/MoonshotAI/kimi-cli",
        "iconUrl": "https://avatars.githubusercontent.com/MoonshotAI?s=128",
        "installation": {
          "commands": [
            "curl -LsSf https://code.kimi.com/install.sh | bash"
          ],
          "startCommand": "kimi",
          "notes": "Requires curl and bash; the installer sets up uv and the CLI. Run /login inside Kimi. The project is transitioning to Kimi Code; this CLI path remains documented.",
          "setupUrl": "https://moonshotai.github.io/kimi-cli/en/guides/getting-started.html",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "uv tool uninstall kimi-cli"
          ],
          "url": "https://moonshotai.github.io/kimi-cli/en/guides/getting-started.html"
        }
      },
      {
        "id": "mistral-vibe",
        "name": "Mistral Vibe",
        "maker": "Mistral AI",
        "description": "A CLI coding agent that gathers project and Git context and uses tools to carry out changes.",
        "url": "https://github.com/mistralai/mistral-vibe",
        "iconUrl": "https://github.com/mistralai.png?size=128",
        "installation": {
          "commands": [
            "curl -LsSf https://mistral.ai/vibe/install.sh | bash"
          ],
          "startCommand": "vibe",
          "notes": "Requires curl and bash. The installer uses uv to manage Vibe. On first launch, enter your Mistral API key when prompted.",
          "setupUrl": "https://github.com/mistralai/mistral-vibe#installation",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "uv tool uninstall mistral-vibe"
          ],
          "url": "https://mistral.ai/vibe/install.sh"
        }
      },
      {
        "id": "continue",
        "name": "Continue CLI",
        "maker": "Continue",
        "description": "A configurable terminal coding agent with interactive and headless modes, launched as cn.",
        "url": "https://docs.continue.dev/cli/quickstart",
        "iconUrl": "https://avatars.githubusercontent.com/continuedev?s=128",
        "installation": {
          "commands": [
            "curl -fsSL https://raw.githubusercontent.com/continuedev/continue/main/extensions/cli/scripts/install.sh | bash"
          ],
          "startCommand": "cn",
          "notes": "Requires curl and bash; this installer includes its runtime. On first launch, sign in with Continue or enter an Anthropic API key.",
          "setupUrl": "https://docs.continue.dev/cli/quickstart",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "npm uninstall -g @continuedev/cli"
          ],
          "url": "https://github.com/continuedev/continue/blob/main/extensions/cli/scripts/install.sh"
        }
      },
      {
        "id": "kiro",
        "name": "Kiro CLI",
        "maker": "AWS",
        "description": "A terminal development agent with project steering, custom agents, hooks, and headless workflows.",
        "url": "https://kiro.dev/docs/cli/",
        "iconUrl": "https://github.com/kirodotdev.png?size=128",
        "installation": {
          "commands": [
            "curl -fsSL https://cli.kiro.dev/install | bash"
          ],
          "startCommand": "kiro-cli",
          "notes": "Requires curl and bash. Start Kiro CLI in your project and complete the interactive sign-in flow.",
          "setupUrl": "https://kiro.dev/docs/cli/",
          "platforms": [
            "macos",
            "linux"
          ]
        },
        "uninstall": {
          "commands": [
            "kiro-cli uninstall"
          ],
          "url": "https://kiro.dev/docs/getting-started/installation/#uninstalling",
          "note": "The vendor now documents the same kiro-cli uninstall command on macOS and Linux."
        }
      }
    ]
  }
);
